From 2ee5d2aee1c5c22057f0e7c6ca94824687b7361b Mon Sep 17 00:00:00 2001
From: Jan Janssen <jan-janssen@users.noreply.github.com>
Date: Sat, 6 Aug 2022 22:29:47 -0600
Subject: [PATCH] Python 3 Fix

---
 scanpdf/scanpdf.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/scanpdf/scanpdf.py b/scanpdf/scanpdf.py
index b211987..c768940 100644
--- a/scanpdf/scanpdf.py
+++ b/scanpdf/scanpdf.py
@@ -67,7 +67,7 @@ def cmd(self, cmd_list):
             logging.debug(out)
             return out
         except subprocess.CalledProcessError as e:
-            print e.output
+            print(e.output)
             self._error("Could not run command %s" % cmd_list)
             
 
@@ -398,7 +398,7 @@ def go(self, argv):
 def main():
     args = docopt.docopt(__doc__, version='Scan PDF %s' % __version__ )
     script = ScanPdf()
-    print args
+    print(args)
     script.go(args)
 
 if __name__ == '__main__':
