From 85a88abb61af850f6583a16369f11e48a07697e9 Mon Sep 17 00:00:00 2001
From: Jan Janssen <jan-janssen@users.noreply.github.com>
Date: Sat, 6 Aug 2022 22:37:41 -0600
Subject: [PATCH] Fix Python 3

---
 scanpdf/scanpdf.py | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/scanpdf/scanpdf.py b/scanpdf/scanpdf.py
index b211987..3d38ab2 100644
--- a/scanpdf/scanpdf.py
+++ b/scanpdf/scanpdf.py
@@ -38,7 +38,7 @@
 import shutil
 import re
 
-from version import __version__
+from scanpdf.version import __version__
 import docopt
 
 import subprocess
@@ -67,7 +67,7 @@ def cmd(self, cmd_list):
             logging.debug(out)
             return out
         except subprocess.CalledProcessError as e:
-            print e.output
+            print(e.output)
             self._error("Could not run command %s" % cmd_list)
             
 
@@ -398,7 +398,7 @@ def go(self, argv):
 def main():
     args = docopt.docopt(__doc__, version='Scan PDF %s' % __version__ )
     script = ScanPdf()
-    print args
+    print(args)
     script.go(args)
 
 if __name__ == '__main__':
